-- MySQL Script generated by MySQL Workbench
-- Thu Dec 12 11:48:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gestion_atv
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestion_atv
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestion_atv`;
USE `gestion_atv` ;

-- -----------------------------------------------------
-- Table `gestion_atv`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_atv`.`estados` (
  `id_est` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_est`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestion_atv`.`tp_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_atv`.`tp_usuario` (
  `id_tpu` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_tpu`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestion_atv`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_atv`.`usuarios` (
  `id_us` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(25) NOT NULL,
  `pass` VARCHAR(55) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `tipou` INT NOT NULL,
  PRIMARY KEY (`id_us`),
  INDEX `fk_tp_idx` (`tipou` ASC),
  CONSTRAINT `fk_tp`
    FOREIGN KEY (`tipou`)
    REFERENCES `gestion_atv`.`tp_usuario` (`id_tpu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestion_atv`.`actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_atv`.`actividades` (
  `id_atv` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fecha_limite` DATE NOT NULL,
  `est` INT(11) NOT NULL,
  `usu` INT NOT NULL,
  PRIMARY KEY (`id_atv`),
  INDEX `fk_est` (`est` ASC),
  INDEX `fk_u_idx` (`usu` ASC),
  CONSTRAINT `fk_est`
    FOREIGN KEY (`est`)
    REFERENCES `gestion_atv`.`estados` (`id_est`),
  CONSTRAINT `fk_u`
    FOREIGN KEY (`usu`)
    REFERENCES `gestion_atv`.`usuarios` (`id_us`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestion_atv`.`tipo_face`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_atv`.`tipo_face` (
  `id_tf` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_tf`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestion_atv`.`faces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_atv`.`faces` (
  `id_face` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_actu` DATE NOT NULL,
  `act` INT(11) NOT NULL,
  `t_face` INT(11) NOT NULL,
  PRIMARY KEY (`id_face`),
  INDEX `fk_ac` (`act` ASC),
  INDEX `fk_tf` (`t_face` ASC),
  CONSTRAINT `fk_ac`
    FOREIGN KEY (`act`)
    REFERENCES `gestion_atv`.`actividades` (`id_atv`),
  CONSTRAINT `fk_tf`
    FOREIGN KEY (`t_face`)
    REFERENCES `gestion_atv`.`tipo_face` (`id_tf`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestion_atv`.`fechas_especiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_atv`.`fechas_especiales` (
  `id_fe` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `dia_feriado` DATE NULL DEFAULT NULL,
  `inicio_vacacion` DATE NULL DEFAULT NULL,
  `fin_vacacion` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_fe`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestion_atv`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_atv`.`personas` (
  `id_per` INT(11) NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(200) NOT NULL,
  `apelliodos` VARCHAR(200) NOT NULL,
  `dui` VARCHAR(16) NOT NULL,
  `fecha_na` DATE NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `usu` INT(11) NOT NULL,
  PRIMARY KEY (`id_per`),
  UNIQUE INDEX `dui` (`dui` ASC),
  INDEX `fk_usu` (`usu` ASC),
  CONSTRAINT `fk_usu`
    FOREIGN KEY (`usu`)
    REFERENCES `gestion_atv`.`usuarios` (`id_us`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
