package com.a.models;
// Generated 12-12-2019 01:17:38 PM by Hibernate Tools 5.2.12.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Actividades generated by hbm2java
 */
@Entity
@SuppressWarnings("serial")
@Table(name = "actividades", catalog = "gestion_atv")
public class Actividades implements java.io.Serializable {

	private int idAtv;
	private Estados estados;
	private Usuarios usuarios;
	private String nombre;
	private String descripcion;
	private Date fechaLimite;
	private List<Faces> faceses = new ArrayList<Faces>();

	public Actividades() {
	}

	public Actividades(int idAtv, Estados estados, Usuarios usuarios, String nombre, String descripcion,
			Date fechaLimite) {
		this.idAtv = idAtv;
		this.estados = estados;
		this.usuarios = usuarios;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.fechaLimite = fechaLimite;
	}

	public Actividades(int idAtv, Estados estados, Usuarios usuarios, String nombre, String descripcion,
			Date fechaLimite, List<Faces> faceses) {
		this.idAtv = idAtv;
		this.estados = estados;
		this.usuarios = usuarios;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.fechaLimite = fechaLimite;
		this.faceses = faceses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id_atv", unique = true, nullable = false)
	public int getIdAtv() {
		return this.idAtv;
	}

	public void setIdAtv(int idAtv) {
		this.idAtv = idAtv;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "est", nullable = false)
	public Estados getEstados() {
		return this.estados;
	}

	public void setEstados(Estados estados) {
		this.estados = estados;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usu", nullable = false)
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", nullable = false, length = 65535)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_limite", nullable = false, length = 10)
	public Date getFechaLimite() {
		return this.fechaLimite;
	}

	public void setFechaLimite(Date fechaLimite) {
		this.fechaLimite = fechaLimite;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actividades")
	public List<Faces> getFaceses() {
		return this.faceses;
	}

	public void setFaceses(List<Faces> faceses) {
		this.faceses = faceses;
	}

}
