package com.a.models;
// Generated 12-12-2019 01:17:38 PM by Hibernate Tools 5.2.12.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estados generated by hbm2java
 */
@Entity
@SuppressWarnings("serial")
@Table(name = "estados", catalog = "gestion_atv")
public class Estados implements java.io.Serializable {

	private int idEst;
	private String estado;
	private List<Actividades> actividadeses = new ArrayList<Actividades>();

	public Estados() {
	}

	public Estados(int idEst, String estado) {
		this.idEst = idEst;
		this.estado = estado;
	}

	public Estados(int idEst, String estado, List<Actividades> actividadeses) {
		this.idEst = idEst;
		this.estado = estado;
		this.actividadeses = actividadeses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	
	@Column(name = "id_est", unique = true, nullable = false)
	public int getIdEst() {
		return this.idEst;
	}

	public void setIdEst(int idEst) {
		this.idEst = idEst;
	}

	@Column(name = "estado", nullable = false, length = 60)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estados")
	public List<Actividades> getActividadeses() {
		return this.actividadeses;
	}

	public void setActividadeses(List<Actividades> actividadeses) {
		this.actividadeses = actividadeses;
	}

}
