package com.a.models;
// Generated 12-12-2019 01:17:38 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FechasEspeciales generated by hbm2java
 */
@Entity
@SuppressWarnings("serial")
@Table(name = "fechas_especiales", catalog = "gestion_atv")
public class FechasEspeciales implements java.io.Serializable {

	private int idFe;
	private String descripcion;
	private Date diaFeriado;
	private Date inicioVacacion;
	private Date finVacacion;

	public FechasEspeciales() {
	}

	public FechasEspeciales(int idFe) {
		this.idFe = idFe;
	}

	public FechasEspeciales(int idFe, String descripcion, Date diaFeriado, Date inicioVacacion, Date finVacacion) {
		this.idFe = idFe;
		this.descripcion = descripcion;
		this.diaFeriado = diaFeriado;
		this.inicioVacacion = inicioVacacion;
		this.finVacacion = finVacacion;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id_fe", unique = true, nullable = false)
	public int getIdFe() {
		return this.idFe;
	}

	public void setIdFe(int idFe) {
		this.idFe = idFe;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dia_feriado", length = 10)
	public Date getDiaFeriado() {
		return this.diaFeriado;
	}

	public void setDiaFeriado(Date diaFeriado) {
		this.diaFeriado = diaFeriado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "inicio_vacacion", length = 10)
	public Date getInicioVacacion() {
		return this.inicioVacacion;
	}

	public void setInicioVacacion(Date inicioVacacion) {
		this.inicioVacacion = inicioVacacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fin_vacacion", length = 10)
	public Date getFinVacacion() {
		return this.finVacacion;
	}

	public void setFinVacacion(Date finVacacion) {
		this.finVacacion = finVacacion;
	}

}
