package com.a.models;
// Generated 12-12-2019 01:17:38 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Personas generated by hbm2java
 */
@Entity
@SuppressWarnings("serial")
@Table(name = "personas", catalog = "gestion_atv", uniqueConstraints = @UniqueConstraint(columnNames = "dui"))
public class Personas implements java.io.Serializable {

	private int idPer;
	private Usuarios usuarios;
	private String nombres;
	private String apelliodos;
	private String dui;
	private Date fechaNa;
	private boolean estado;
	private char sexo;

	public Personas() {
	}

	public Personas(int idPer, Usuarios usuarios, String nombres, String apelliodos, String dui, Date fechaNa,
			boolean estado, char sexo) {
		this.idPer = idPer;
		this.usuarios = usuarios;
		this.nombres = nombres;
		this.apelliodos = apelliodos;
		this.dui = dui;
		this.fechaNa = fechaNa;
		this.estado = estado;
		this.sexo = sexo;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id_per", unique = true, nullable = false)
	public int getIdPer() {
		return this.idPer;
	}

	public void setIdPer(int idPer) {
		this.idPer = idPer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usu", nullable = false)
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@Column(name = "nombres", nullable = false, length = 200)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "apelliodos", nullable = false, length = 200)
	public String getApelliodos() {
		return this.apelliodos;
	}

	public void setApelliodos(String apelliodos) {
		this.apelliodos = apelliodos;
	}

	@Column(name = "dui", unique = true, nullable = false, length = 16)
	public String getDui() {
		return this.dui;
	}

	public void setDui(String dui) {
		this.dui = dui;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_na", nullable = false, length = 10)
	public Date getFechaNa() {
		return this.fechaNa;
	}

	public void setFechaNa(Date fechaNa) {
		this.fechaNa = fechaNa;
	}

	@Column(name = "estado", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@Column(name = "sexo", nullable = false, length = 1)
	public char getSexo() {
		return this.sexo;
	}

	public void setSexo(char sexo) {
		this.sexo = sexo;
	}

}
