package com.a.models;
// Generated 12-12-2019 01:17:38 PM by Hibernate Tools 5.2.12.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoFace generated by hbm2java
 */
@Entity
@SuppressWarnings("serial")
@Table(name = "tipo_face", catalog = "gestion_atv")
public class TipoFace implements java.io.Serializable {

	private int idTf;
	private String descripcion;
	private List<Faces> faceses = new ArrayList<Faces>();

	public TipoFace() {
	}

	public TipoFace(int idTf, String descripcion) {
		this.idTf = idTf;
		this.descripcion = descripcion;
	}

	public TipoFace(int idTf, String descripcion, List<Faces> faceses) {
		this.idTf = idTf;
		this.descripcion = descripcion;
		this.faceses = faceses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id_tf", unique = true, nullable = false)
	public int getIdTf() {
		return this.idTf;
	}

	public void setIdTf(int idTf) {
		this.idTf = idTf;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoFace")
	public List<Faces> getFaceses() {
		return this.faceses;
	}

	public void setFaceses(List<Faces> faceses) {
		this.faceses = faceses;
	}

}
