package com.a.models;
// Generated 12-12-2019 01:17:38 PM by Hibernate Tools 5.2.12.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TpUsuario generated by hbm2java
 */
@Entity
@SuppressWarnings("serial")
@Table(name = "tp_usuario", catalog = "gestion_atv")
public class TpUsuario implements java.io.Serializable {

	private int idTpu;
	private String tipo;
	private List<Usuarios> usuarioses = new ArrayList<Usuarios>();

	public TpUsuario() {
	}

	public TpUsuario(int idTpu, String tipo) {
		this.idTpu = idTpu;
		this.tipo = tipo;
	}

	public TpUsuario(int idTpu, String tipo, List<Usuarios> usuarioses) {
		this.idTpu = idTpu;
		this.tipo = tipo;
		this.usuarioses = usuarioses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id_tpu", unique = true, nullable = false)
	public int getIdTpu() {
		return this.idTpu;
	}

	public void setIdTpu(int idTpu) {
		this.idTpu = idTpu;
	}

	@Column(name = "tipo", nullable = false, length = 60)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tpUsuario")
	public List<Usuarios> getUsuarioses() {
		return this.usuarioses;
	}

	public void setUsuarioses(List<Usuarios> usuarioses) {
		this.usuarioses = usuarioses;
	}

}
