package com.a.models;
// Generated 12-12-2019 01:17:38 PM by Hibernate Tools 5.2.12.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@SuppressWarnings("serial")
@Table(name = "usuarios", catalog = "gestion_atv")
public class Usuarios implements java.io.Serializable {

	private int idUs;
	private TpUsuario tpUsuario;
	private String username;
	private String pass;
	private boolean estado;
	private List<Personas> personases = new ArrayList<Personas>();
	private List<Actividades> actividadeses = new ArrayList<Actividades>();

	public Usuarios() {
	}

	public Usuarios(int idUs, TpUsuario tpUsuario, String username, String pass, boolean estado) {
		this.idUs = idUs;
		this.tpUsuario = tpUsuario;
		this.username = username;
		this.pass = pass;
		this.estado = estado;
	}

	public Usuarios(int idUs, TpUsuario tpUsuario, String username, String pass, boolean estado, List<Personas> personases,
			List<Actividades> actividadeses) {
		this.idUs = idUs;
		this.tpUsuario = tpUsuario;
		this.username = username;
		this.pass = pass;
		this.estado = estado;
		this.personases = personases;
		this.actividadeses = actividadeses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id_us", unique = true, nullable = false)
	public int getIdUs() {
		return this.idUs;
	}

	public void setIdUs(int idUs) {
		this.idUs = idUs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipou", nullable = false)
	public TpUsuario getTpUsuario() {
		return this.tpUsuario;
	}

	public void setTpUsuario(TpUsuario tpUsuario) {
		this.tpUsuario = tpUsuario;
	}

	@Column(name = "username", nullable = false, length = 25)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "pass", nullable = false, length = 55)
	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	@Column(name = "estado", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarios")
	public List<Personas> getPersonases() {
		return this.personases;
	}

	public void setPersonases(List<Personas> personases) {
		this.personases = personases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarios")
	public List<Actividades> getActividadeses() {
		return this.actividadeses;
	}

	public void setActividadeses(List<Actividades> actividadeses) {
		this.actividadeses = actividadeses;
	}

}
